<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function buddyx_child_enqueue_styles() {
    wp_enqueue_style( 'buddyx-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'buddyx-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'buddyx-style' ),
        wp_get_theme()->get('Version')
    );
    wp_enqueue_style( 'buddyx-child-icons', get_stylesheet_directory_uri() . '/style-icons.css', array( 'buddyx-style' ), wp_get_theme()->get('Version'));
}

add_action(  'wp_enqueue_scripts', 'buddyx_child_enqueue_styles' );

/**
 * Enqueue scripts and styles.
 */

add_action( 'wp_enqueue_scripts', 'bootstrap46_scripts' );
function bootstrap46_scripts() {
  //function bootstrap46_scripts() : void {

	wp_enqueue_style('wpdocs-bootstrap-style', 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css' );
  /* SCRIPTS */
  wp_enqueue_script( 'wpdocs-bootstrap-bundle-script', 'https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js', array(), null, true );
  wp_enqueue_script( 'wpdocs-jquery-datatables-script', 'https://code.jquery.com/jquery-3.5.1.min.js', array(), null, true );    
   

  // Add filters to catch and modify the styles and scripts as they're loaded.
  add_filter( 'style_loader_tag', __NAMESPACE__ . '\wpdocs_my_add_sri', 10, 2 );
  add_filter( 'script_loader_tag', __NAMESPACE__ . '\wpdocs_my_add_sri', 10, 2 );
}


/**
* Add SRI attributes based on defined script/style handles.
*/
function wpdocs_my_add_sri( $html, $handle ) : string {
  switch( $handle ) {
      case 'wpdocs-bootstrap-style':
          $html = str_replace( ' />', ' integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous" />', $html );
          break;
      case 'wpdocs-bootstrap-bundle-script':
          $html = str_replace( '></script>', ' integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>', $html );
          break;
      case 'wpdocs-jquery-datatables-script':
          $html = str_replace( '></script>', ' integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>', $html );
          break;
  } 
  return $html;
}


/**
 * Custom Login
 */
//require get_template_directory() . '/inc/custom-login.php';
require get_theme_file_path(  'inc/custom-login.php' );


if ( !defined( 'BP_AVATAR_THUMB_WIDTH' ) )
define( 'BP_AVATAR_THUMB_WIDTH', 150 );

if ( !defined( 'BP_AVATAR_THUMB_HEIGHT' ) )
define( 'BP_AVATAR_THUMB_HEIGHT', 150 );

if ( !defined( 'BP_AVATAR_FULL_WIDTH' ) )
define( 'BP_AVATAR_FULL_WIDTH', 350 );

if ( !defined( 'BP_AVATAR_FULL_HEIGHT' ) )
define( 'BP_AVATAR_FULL_HEIGHT', 350 );

if ( !defined( 'BP_AVATAR_ORIGINAL_MAX_WIDTH' ) )
define( 'BP_AVATAR_ORIGINAL_MAX_WIDTH', 600 );


function format_activity_date() {
  $activityDate=bp_get_activity_date_recorded();
  if ($activityDate>strtotime(24)){
  return date('d/m/Y \a \l\a\s g:ia', strtotime($activityDate));
  }
  else
  {$activityDate;}
  
  }
  add_filter('bp_activity_time_since', 'format_activity_date');


